# This is a basic workflow to help you get started with Actions

name: Build default firmware for BLE Micro Pro

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev/ble_micro_pro branch
  push:
    branches: [ dev/ble_micro_pro ]
  pull_request:
    branches: [ dev/ble_micro_pro ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container: qmkfm/base_container
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: python3 -m pip install qmk
      
      # Runs a single command using the runners shell
      - name: git config
        run: git config --global --add safe.directory /__w/qmk_firmware/qmk_firmware
        
      - name: Build ble_micro_pro firmware
        run: make ble_micro_pro:default:uf2
        
      - name: Build keyboard_quantizer_b firmware
        run: make keyboard_quantizer/kqb:default:uf2
     
      - uses: actions/upload-artifact@v2
        with:
          name: default_firmware_uf2
          path: ./*.uf2
      
